import { Schedule } from 'src/types';

export const schedules = [
  {
    _id: 'sampleScheduleId1',
    date: '2022-08-08',
    flag: 'daily',
    estimatedTime: [],
    usedTime: [],
    title: '드래그미 회의',
    subSchedules: [
      {
        _id: 'sampleSubScheduleId',
      },
      {
        _id: 'sampleSubScheduleId2',
      },
    ],
    categoryColorCode: '#7B8DD8',
    userId: 'sampleUserId',
    isCompleted: true,
    isReschedule: false,
    isRoutine: false,
    orderIndex: 1,
  },
  {
    _id: 'sampleScheduleId2',
    date: '2022-08-08',
    flag: 'daily',
    estimatedTime: [],
    usedTime: [],
    title: '샤워하기',
    subSchedules: [],
    categoryColorCode: '#F67F6F',
    userId: 'sampleUserId',
    isCompleted: false,
    isReschedule: false,
    isRoutine: false,
    orderIndex: 1,
  },
  {
    _id: 'sampleScheduleId3',
    date: '2022-08-08',
    flag: 'daily',
    estimatedTime: [],
    usedTime: [],
    title: '수학 공부하기',
    subSchedules: [],
    categoryColorCode: '#EAC96E',
    userId: 'sampleUserId',
    isCompleted: false,
    isReschedule: false,
    isRoutine: false,
    orderIndex: 1,
  },
  {
    _id: 'sampleScheduleId4',
    date: '2022-08-08',
    flag: 'daily',
    estimatedTime: [],
    usedTime: [],
    title: '국어 공부하기',
    subSchedules: [],
    categoryColorCode: '#F67F6F',
    userId: 'sampleUserId',
    isCompleted: false,
    isReschedule: false,
    isRoutine: false,
    orderIndex: 1,
  },
  {
    _id: 'sampleScheduleId5',
    date: '2022-08-08',
    flag: 'daily',
    estimatedTime: [],
    usedTime: [],
    title: '외주',
    subSchedules: [
      {
        _id: 'sampleSubScheduleId',
      },
      {
        _id: 'sampleSubScheduleId2',
      },
    ],
    categoryColorCode: '#95B39C',
    userId: 'sampleUserId',
    isCompleted: true,
    isReschedule: false,
    isRoutine: false,
    orderIndex: 1,
  },
  {
    _id: 'sampleScheduleId6',
    date: '2022-08-08',
    flag: 'daily',
    estimatedTime: [],
    usedTime: [],
    title: '맛있는 거 사오기',
    subSchedules: [
      {
        _id: 'sampleSubScheduleId',
      },
      {
        _id: 'sampleSubScheduleId2',
      },
    ],
    categoryColorCode: '#F67F6F',
    userId: 'sampleUserId',
    isCompleted: false,
    isReschedule: false,
    isRoutine: false,
    orderIndex: 1,
  },
  {
    _id: 'sampleScheduleId7',
    date: '2022-08-08',
    flag: 'daily',
    estimatedTime: [],
    usedTime: [],
    title: '잠 자기',
    subSchedules: [],
    categoryColorCode: '#96CCC9',
    userId: 'sampleUserId',
    isCompleted: false,
    isReschedule: false,
    isRoutine: false,
    orderIndex: 1,
  },
  {
    _id: 'sampleScheduleId8',
    date: '2022-08-08',
    flag: 'daily',
    estimatedTime: [],
    usedTime: [],
    title: '외주 작업 하기',
    subSchedules: [],
    categoryColorCode: '#DCADC8',
    userId: 'sampleUserId',
    isCompleted: false,
    isReschedule: false,
    isRoutine: false,
    orderIndex: 1,
  },
  {
    _id: 'sampleScheduleId9',
    date: '2022-08-08',
    flag: 'daily',
    estimatedTime: [],
    usedTime: [],
    title: '팀플 회의하기',
    subSchedules: [],
    categoryColorCode: '#7B8DD8',
    userId: 'sampleUserId',
    isCompleted: false,
    isReschedule: false,
    isRoutine: false,
    orderIndex: 1,
  },
  {
    _id: 'sampleScheduleId10',
    date: '2022-08-08',
    flag: 'daily',
    estimatedTime: [],
    usedTime: [],
    title: '드래그미랑 놀기 !',
    subSchedules: [],
    categoryColorCode: '#F67F6F',
    userId: 'sampleUserId',
    isCompleted: false,
    isReschedule: false,
    isRoutine: false,
    orderIndex: 1,
  },
];
export const reschedules = [
  {
    _id: 'sampleScheduleId11',
    date: '2022-08-08',
    flag: 'reschedule',
    estimatedTime: [],
    usedTime: [],
    title: '드래그미 회의',
    subSchedules: [
      {
        _id: 'sampleSubScheduleId',
      },
      {
        _id: 'sampleSubScheduleId2',
      },
    ],
    categoryColorCode: '#7B8DD8',
    userId: 'sampleUserId',
    isCompleted: true,
    isReschedule: false,
    isRoutine: false,
    orderIndex: 1,
  },
  {
    _id: 'sampleScheduleId12',
    date: '2022-08-08',
    flag: 'reschedule',
    estimatedTime: [],
    usedTime: [],
    title: '샤워하기',
    subSchedules: [],
    categoryColorCode: '#F67F6F',
    userId: 'sampleUserId',
    isCompleted: false,
    isReschedule: false,
    isRoutine: false,
    orderIndex: 1,
  },
  {
    _id: 'sampleScheduleId13',
    date: '2022-08-08',
    flag: 'reschedule',
    estimatedTime: [],
    usedTime: [],
    title: '수학 공부하기',
    subSchedules: [],
    categoryColorCode: '#EAC96E',
    userId: 'sampleUserId',
    isCompleted: false,
    isReschedule: false,
    isRoutine: false,
    orderIndex: 1,
  },
  {
    _id: 'sampleScheduleId14',
    date: '2022-08-08',
    flag: 'reschedule',
    estimatedTime: [],
    usedTime: [],
    title: '국어 공부하기',
    subSchedules: [],
    categoryColorCode: '#F67F6F',
    userId: 'sampleUserId',
    isCompleted: false,
    isReschedule: false,
    isRoutine: false,
    orderIndex: 1,
  },
  {
    _id: 'sampleScheduleId15',
    date: '2022-08-08',
    flag: 'reschedule',
    estimatedTime: [],
    usedTime: [],
    title: '외주',
    subSchedules: [
      {
        _id: 'sampleSubScheduleId',
      },
      {
        _id: 'sampleSubScheduleId2',
      },
    ],
    categoryColorCode: '#95B39C',
    userId: 'sampleUserId',
    isCompleted: true,
    isReschedule: false,
    isRoutine: false,
    orderIndex: 1,
  },
  {
    _id: 'sampleScheduleId16',
    date: '2022-08-08',
    flag: 'reschedule',
    estimatedTime: [],
    usedTime: [],
    title: '맛있는 거 사오기',
    subSchedules: [
      {
        _id: 'sampleSubScheduleId',
      },
      {
        _id: 'sampleSubScheduleId2',
      },
    ],
    categoryColorCode: '#F67F6F',
    userId: 'sampleUserId',
    isCompleted: false,
    isReschedule: false,
    isRoutine: false,
    orderIndex: 1,
  },
  {
    _id: 'sampleScheduleId17',
    date: '2022-08-08',
    flag: 'reschedule',
    estimatedTime: [],
    usedTime: [],
    title: '잠 자기',
    subSchedules: [],
    categoryColorCode: '#96CCC9',
    userId: 'sampleUserId',
    isCompleted: false,
    isReschedule: false,
    isRoutine: false,
    orderIndex: 1,
  },
  {
    _id: 'sampleScheduleId18',
    date: '2022-08-08',
    flag: 'reschedule',
    estimatedTime: [],
    usedTime: [],
    title: '외주 작업 하기',
    subSchedules: [],
    categoryColorCode: '#DCADC8',
    userId: 'sampleUserId',
    isCompleted: false,
    isReschedule: false,
    isRoutine: false,
    orderIndex: 1,
  },
  {
    _id: 'sampleScheduleId19',
    date: '2022-08-08',
    flag: 'reschedule',
    estimatedTime: [],
    usedTime: [],
    title: '팀플 회의하기',
    subSchedules: [],
    categoryColorCode: '#7B8DD8',
    userId: 'sampleUserId',
    isCompleted: false,
    isReschedule: false,
    isRoutine: false,
    orderIndex: 1,
  },
  {
    _id: 'sampleScheduleId20',
    date: '2022-08-08',
    flag: 'reschedule',
    estimatedTime: [],
    usedTime: [],
    title: '드래그미랑 놀기 !',
    subSchedules: [],
    categoryColorCode: '#F67F6F',
    userId: 'sampleUserId',
    isCompleted: false,
    isReschedule: false,
    isRoutine: false,
    orderIndex: 1,
  },
];

export const routineSchedules = [
  {
    _id: 'sampleScheduleId111',
    date: '2022-08-08',
    flag: 'routine',
    estimatedTime: [],
    usedTime: [],
    title: '드래그미 회의',
    subSchedules: [
      {
        _id: 'sampleSubScheduleId',
      },
      {
        _id: 'sampleSubScheduleId21',
      },
    ],
    categoryColorCode: '#7B8DD8',
    userId: 'sampleUserId',
    isCompleted: true,
    isReschedule: false,
    isRoutine: false,
    orderIndex: 1,
  },
  {
    _id: 'sampleScheduleId1211',
    date: '2022-08-08',
    flag: 'routine',
    estimatedTime: [],
    usedTime: [],
    title: '샤워하기',
    subSchedules: [],
    categoryColorCode: '#F67F6F',
    userId: 'sampleUserId',
    isCompleted: false,
    isReschedule: false,
    isRoutine: false,
    orderIndex: 1,
  },
  {
    _id: 'sampleScheduleId1311',
    date: '2022-08-08',
    flag: 'routine',
    estimatedTime: [],
    usedTime: [],
    title: '수학 공부하기',
    subSchedules: [],
    categoryColorCode: '#EAC96E',
    userId: 'sampleUserId',
    isCompleted: false,
    isReschedule: false,
    isRoutine: false,
    orderIndex: 1,
  },
  {
    _id: 'sampleScheduleId1411',
    date: '2022-08-08',
    flag: 'routine',
    estimatedTime: [],
    usedTime: [],
    title: '국어 공부하기',
    subSchedules: [],
    categoryColorCode: '#F67F6F',
    userId: 'sampleUserId',
    isCompleted: false,
    isReschedule: false,
    isRoutine: false,
    orderIndex: 1,
  },
  {
    _id: 'sampleScheduleId1511',
    date: '2022-08-08',
    flag: 'routine',
    estimatedTime: [],
    usedTime: [],
    title: '외주',
    subSchedules: [
      {
        _id: 'sampleSubScheduleId',
      },
      {
        _id: 'sampleSubScheduleId2',
      },
    ],
    categoryColorCode: '#95B39C',
    userId: 'sampleUserId',
    isCompleted: true,
    isReschedule: false,
    isRoutine: false,
    orderIndex: 1,
  },
  {
    _id: 'sampleScheduleId1611',
    date: '2022-08-08',
    flag: 'routine',
    estimatedTime: [],
    usedTime: [],
    title: '맛있는 거 사오기',
    subSchedules: [
      {
        _id: 'sampleSubScheduleId',
      },
      {
        _id: 'sampleSubScheduleId2',
      },
    ],
    categoryColorCode: '#F67F6F',
    userId: 'sampleUserId',
    isCompleted: false,
    isReschedule: false,
    isRoutine: false,
    orderIndex: 1,
  },
  {
    _id: 'sampleScheduleId1711',
    date: '2022-08-08',
    flag: 'routine',
    estimatedTime: [],
    usedTime: [],
    title: '잠 자기',
    subSchedules: [],
    categoryColorCode: '#96CCC9',
    userId: 'sampleUserId',
    isCompleted: false,
    isReschedule: false,
    isRoutine: false,
    orderIndex: 1,
  },
  {
    _id: 'sampleScheduleId1811',
    date: '2022-08-08',
    flag: 'routine',
    estimatedTime: [],
    usedTime: [],
    title: '외주 작업 하기',
    subSchedules: [],
    categoryColorCode: '#DCADC8',
    userId: 'sampleUserId',
    isCompleted: false,
    isReschedule: false,
    isRoutine: false,
    orderIndex: 1,
  },
  {
    _id: 'sampleScheduleId1911',
    date: '2022-08-08',
    flag: 'routine',
    estimatedTime: [],
    usedTime: [],
    title: '팀플 회의하기',
    subSchedules: [],
    categoryColorCode: '#7B8DD8',
    userId: 'sampleUserId',
    isCompleted: false,
    isReschedule: false,
    isRoutine: false,
    orderIndex: 1,
  },
  {
    _id: 'sampleScheduleId2011',
    date: '2022-08-08',
    flag: 'routine',
    estimatedTime: [],
    usedTime: [],
    title: '드래그미랑 놀기 !',
    subSchedules: [],
    categoryColorCode: '#F67F6F',
    userId: 'sampleUserId',
    isCompleted: false,
    isReschedule: false,
    isRoutine: false,
    orderIndex: 1,
  },
];

//서버 제거로 인한 임시 목 데이터
export const timeBlockSchedules: Schedule[] = [
  {
    _id: 'sampleScheduleId1',
    date: '2022-08-08',
    estimatedTime: [1, 2, 3],
    usedTime: [4, 5, 6],
    title: '드래그미 회의',
    subSchedules: ['sampleSubScheduleId', 'sampleSubScheduleId2'],
    categoryColorCode: '#7B8DD8',
    userId: 'sampleUserId',
    isCompleted: true,
    isReschedule: false,
    isRoutine: false,
    orderIndex: 1,
    createdAt: '12111',
    updatedAt: '1222',
  },
];
