export const theme = {
  colors: {
    main_color: '#0A42DF',
    plan_check: '#D0D4DA',
    plan_grey: '#B6BEC9',
    week_line: '#7E839A',
    letter_black: '#333333',
    letter_grey: '#D8DBDE',
    hour_line: '#E3E6EA',
    hour_background: '#FCFDFD',
    hour_fill: '#B8C1F0',
    scroll_grey: '#F8F9FB',
    calender_future: '#DADFF7',
  },
  category: {
    cate_blue: '#7B8DD8',
    cate_pink: '#DCADC8',
    cate_purple: '#CEB9EA',
    cate_yellow: '#EAC96E',
    cate_green: '#95B39C',
    cate_corarl: 'F67F6F',
    cate_white: '#FFFFFF',
    cate_mint: '#96CCC9',
  },
};
